package com.revers.rec.domain.protobuf;// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProtocal.proto

public final class MsgProtobuf {
  private MsgProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface connectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:connection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string srcId = 1;</code>
     * @return The srcId.
     */
    String getSrcId();
    /**
     * <code>string srcId = 1;</code>
     * @return The bytes for srcId.
     */
    com.google.protobuf.ByteString
        getSrcIdBytes();

    /**
     * <code>string destId = 2;</code>
     * @return The destId.
     */
    String getDestId();
    /**
     * <code>string destId = 2;</code>
     * @return The bytes for destId.
     */
    com.google.protobuf.ByteString
        getDestIdBytes();

    /**
     * <code>string srcPublicKey = 3;</code>
     * @return The srcPublicKey.
     */
    String getSrcPublicKey();
    /**
     * <code>string srcPublicKey = 3;</code>
     * @return The bytes for srcPublicKey.
     */
    com.google.protobuf.ByteString
        getSrcPublicKeyBytes();

    /**
     * <code>string destPublicKey = 4;</code>
     * @return The destPublicKey.
     */
    String getDestPublicKey();
    /**
     * <code>string destPublicKey = 4;</code>
     * @return The bytes for destPublicKey.
     */
    com.google.protobuf.ByteString
        getDestPublicKeyBytes();

    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    String getData();
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code connection}
   */
  public static final class connection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:connection)
      connectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use connection.newBuilder() to construct.
    private connection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private connection() {
      srcId_ = "";
      destId_ = "";
      srcPublicKey_ = "";
      destPublicKey_ = "";
      data_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new connection();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private connection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              srcId_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              destId_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              srcPublicKey_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              destPublicKey_ = s;
              break;
            }
            case 42: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProtobuf.internal_static_connection_descriptor;
    }

    @Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProtobuf.internal_static_connection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              connection.class, Builder.class);
    }

    public static final int SRCID_FIELD_NUMBER = 1;
    private volatile Object srcId_;
    /**
     * <code>string srcId = 1;</code>
     * @return The srcId.
     */
    @Override
    public String getSrcId() {
      Object ref = srcId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        srcId_ = s;
        return s;
      }
    }
    /**
     * <code>string srcId = 1;</code>
     * @return The bytes for srcId.
     */
    @Override
    public com.google.protobuf.ByteString
        getSrcIdBytes() {
      Object ref = srcId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        srcId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTID_FIELD_NUMBER = 2;
    private volatile Object destId_;
    /**
     * <code>string destId = 2;</code>
     * @return The destId.
     */
    @Override
    public String getDestId() {
      Object ref = destId_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destId_ = s;
        return s;
      }
    }
    /**
     * <code>string destId = 2;</code>
     * @return The bytes for destId.
     */
    @Override
    public com.google.protobuf.ByteString
        getDestIdBytes() {
      Object ref = destId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SRCPUBLICKEY_FIELD_NUMBER = 3;
    private volatile Object srcPublicKey_;
    /**
     * <code>string srcPublicKey = 3;</code>
     * @return The srcPublicKey.
     */
    @Override
    public String getSrcPublicKey() {
      Object ref = srcPublicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        srcPublicKey_ = s;
        return s;
      }
    }
    /**
     * <code>string srcPublicKey = 3;</code>
     * @return The bytes for srcPublicKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getSrcPublicKeyBytes() {
      Object ref = srcPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        srcPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTPUBLICKEY_FIELD_NUMBER = 4;
    private volatile Object destPublicKey_;
    /**
     * <code>string destPublicKey = 4;</code>
     * @return The destPublicKey.
     */
    @Override
    public String getDestPublicKey() {
      Object ref = destPublicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destPublicKey_ = s;
        return s;
      }
    }
    /**
     * <code>string destPublicKey = 4;</code>
     * @return The bytes for destPublicKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getDestPublicKeyBytes() {
      Object ref = destPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATA_FIELD_NUMBER = 5;
    private volatile Object data_;
    /**
     * <code>string data = 5;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 5;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destId_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcPublicKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, srcPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destPublicKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, destPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destId_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destId_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcPublicKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, srcPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destPublicKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, destPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof connection)) {
        return super.equals(obj);
      }
      connection other = (connection) obj;

      if (!getSrcId()
          .equals(other.getSrcId())) return false;
      if (!getDestId()
          .equals(other.getDestId())) return false;
      if (!getSrcPublicKey()
          .equals(other.getSrcPublicKey())) return false;
      if (!getDestPublicKey()
          .equals(other.getDestPublicKey())) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRCID_FIELD_NUMBER;
      hash = (53 * hash) + getSrcId().hashCode();
      hash = (37 * hash) + DESTID_FIELD_NUMBER;
      hash = (53 * hash) + getDestId().hashCode();
      hash = (37 * hash) + SRCPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSrcPublicKey().hashCode();
      hash = (37 * hash) + DESTPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getDestPublicKey().hashCode();
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static connection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static connection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static connection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static connection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static connection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static connection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static connection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(connection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code connection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:connection)
        connectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProtobuf.internal_static_connection_descriptor;
      }

      @Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProtobuf.internal_static_connection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                connection.class, Builder.class);
      }

      // Construct using MsgProtobuf.connection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        srcId_ = "";

        destId_ = "";

        srcPublicKey_ = "";

        destPublicKey_ = "";

        data_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgProtobuf.internal_static_connection_descriptor;
      }

      @Override
      public connection getDefaultInstanceForType() {
        return connection.getDefaultInstance();
      }

      @Override
      public connection build() {
        connection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public connection buildPartial() {
        connection result = new connection(this);
        result.srcId_ = srcId_;
        result.destId_ = destId_;
        result.srcPublicKey_ = srcPublicKey_;
        result.destPublicKey_ = destPublicKey_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof connection) {
          return mergeFrom((connection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(connection other) {
        if (other == connection.getDefaultInstance()) return this;
        if (!other.getSrcId().isEmpty()) {
          srcId_ = other.srcId_;
          onChanged();
        }
        if (!other.getDestId().isEmpty()) {
          destId_ = other.destId_;
          onChanged();
        }
        if (!other.getSrcPublicKey().isEmpty()) {
          srcPublicKey_ = other.srcPublicKey_;
          onChanged();
        }
        if (!other.getDestPublicKey().isEmpty()) {
          destPublicKey_ = other.destPublicKey_;
          onChanged();
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        connection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (connection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object srcId_ = "";
      /**
       * <code>string srcId = 1;</code>
       * @return The srcId.
       */
      public String getSrcId() {
        Object ref = srcId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          srcId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string srcId = 1;</code>
       * @return The bytes for srcId.
       */
      public com.google.protobuf.ByteString
          getSrcIdBytes() {
        Object ref = srcId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          srcId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcId = 1;</code>
       * @param value The srcId to set.
       * @return This builder for chaining.
       */
      public Builder setSrcId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcId() {
        
        srcId_ = getDefaultInstance().getSrcId();
        onChanged();
        return this;
      }
      /**
       * <code>string srcId = 1;</code>
       * @param value The bytes for srcId to set.
       * @return This builder for chaining.
       */
      public Builder setSrcIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcId_ = value;
        onChanged();
        return this;
      }

      private Object destId_ = "";
      /**
       * <code>string destId = 2;</code>
       * @return The destId.
       */
      public String getDestId() {
        Object ref = destId_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          destId_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string destId = 2;</code>
       * @return The bytes for destId.
       */
      public com.google.protobuf.ByteString
          getDestIdBytes() {
        Object ref = destId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destId = 2;</code>
       * @param value The destId to set.
       * @return This builder for chaining.
       */
      public Builder setDestId(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestId() {
        
        destId_ = getDefaultInstance().getDestId();
        onChanged();
        return this;
      }
      /**
       * <code>string destId = 2;</code>
       * @param value The bytes for destId to set.
       * @return This builder for chaining.
       */
      public Builder setDestIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destId_ = value;
        onChanged();
        return this;
      }

      private Object srcPublicKey_ = "";
      /**
       * <code>string srcPublicKey = 3;</code>
       * @return The srcPublicKey.
       */
      public String getSrcPublicKey() {
        Object ref = srcPublicKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          srcPublicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string srcPublicKey = 3;</code>
       * @return The bytes for srcPublicKey.
       */
      public com.google.protobuf.ByteString
          getSrcPublicKeyBytes() {
        Object ref = srcPublicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          srcPublicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcPublicKey = 3;</code>
       * @param value The srcPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setSrcPublicKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcPublicKey = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcPublicKey() {
        
        srcPublicKey_ = getDefaultInstance().getSrcPublicKey();
        onChanged();
        return this;
      }
      /**
       * <code>string srcPublicKey = 3;</code>
       * @param value The bytes for srcPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setSrcPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcPublicKey_ = value;
        onChanged();
        return this;
      }

      private Object destPublicKey_ = "";
      /**
       * <code>string destPublicKey = 4;</code>
       * @return The destPublicKey.
       */
      public String getDestPublicKey() {
        Object ref = destPublicKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          destPublicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string destPublicKey = 4;</code>
       * @return The bytes for destPublicKey.
       */
      public com.google.protobuf.ByteString
          getDestPublicKeyBytes() {
        Object ref = destPublicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destPublicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destPublicKey = 4;</code>
       * @param value The destPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setDestPublicKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destPublicKey = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestPublicKey() {
        
        destPublicKey_ = getDefaultInstance().getDestPublicKey();
        onChanged();
        return this;
      }
      /**
       * <code>string destPublicKey = 4;</code>
       * @param value The bytes for destPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setDestPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destPublicKey_ = value;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>string data = 5;</code>
       * @return The data.
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 5;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 5;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:connection)
    }

    // @@protoc_insertion_point(class_scope:connection)
    private static final connection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new connection();
    }

    public static connection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<connection>
        PARSER = new com.google.protobuf.AbstractParser<connection>() {
      @Override
      public connection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new connection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<connection> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<connection> getParserForType() {
      return PARSER;
    }

    @Override
    public connection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_connection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_connection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021MsgProtocal.proto\"f\n\nconnection\022\r\n\005src" +
      "Id\030\001 \001(\t\022\016\n\006destId\030\002 \001(\t\022\024\n\014srcPublicKey" +
      "\030\003 \001(\t\022\025\n\rdestPublicKey\030\004 \001(\t\022\014\n\004data\030\005 " +
      "\001(\tB\rB\013MsgProtobufb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_connection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_connection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_connection_descriptor,
        new String[] { "SrcId", "DestId", "SrcPublicKey", "DestPublicKey", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
