// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProtocal.proto

package com.revers.rec.domain.protobuf;

public final class MsgProtobuf {
  private MsgProtobuf() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ConnectionOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Connection)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string srcPublicKey = 1;</code>
     * @return The srcPublicKey.
     */
    String getSrcPublicKey();
    /**
     * <code>string srcPublicKey = 1;</code>
     * @return The bytes for srcPublicKey.
     */
    com.google.protobuf.ByteString
        getSrcPublicKeyBytes();

    /**
     * <code>string destPublicKey = 2;</code>
     * @return The destPublicKey.
     */
    String getDestPublicKey();
    /**
     * <code>string destPublicKey = 2;</code>
     * @return The bytes for destPublicKey.
     */
    com.google.protobuf.ByteString
        getDestPublicKeyBytes();

    /**
     * <code>string port = 3;</code>
     * @return The port.
     */
    String getPort();
    /**
     * <code>string port = 3;</code>
     * @return The bytes for port.
     */
    com.google.protobuf.ByteString
        getPortBytes();

    /**
     * <code>string ipv6 = 4;</code>
     * @return The ipv6.
     */
    String getIpv6();
    /**
     * <code>string ipv6 = 4;</code>
     * @return The bytes for ipv6.
     */
    com.google.protobuf.ByteString
        getIpv6Bytes();

    /**
     * <code>uint64 order = 5;</code>
     * @return The order.
     */
    long getOrder();

    /**
     * <code>int32 msgType = 6;</code>
     * @return The msgType.
     */
    int getMsgType();

    /**
     * <code>string signature = 7;</code>
     * @return The signature.
     */
    String getSignature();
    /**
     * <code>string signature = 7;</code>
     * @return The bytes for signature.
     */
    com.google.protobuf.ByteString
        getSignatureBytes();

    /**
     * <code>uint64 timestamp = 8;</code>
     * @return The timestamp.
     */
    long getTimestamp();

    /**
     * <code>string data = 9;</code>
     * @return The data.
     */
    String getData();
    /**
     * <code>string data = 9;</code>
     * @return The bytes for data.
     */
    com.google.protobuf.ByteString
        getDataBytes();
  }
  /**
   * Protobuf type {@code Connection}
   */
  public static final class Connection extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Connection)
      ConnectionOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Connection.newBuilder() to construct.
    private Connection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Connection() {
      srcPublicKey_ = "";
      destPublicKey_ = "";
      port_ = "";
      ipv6_ = "";
      signature_ = "";
      data_ = "";
    }

    @Override
    @SuppressWarnings({"unused"})
    protected Object newInstance(
        UnusedPrivateParameter unused) {
      return new Connection();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Connection(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              srcPublicKey_ = s;
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              destPublicKey_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              port_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              ipv6_ = s;
              break;
            }
            case 40: {

              order_ = input.readUInt64();
              break;
            }
            case 48: {

              msgType_ = input.readInt32();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              signature_ = s;
              break;
            }
            case 64: {

              timestamp_ = input.readUInt64();
              break;
            }
            case 74: {
              String s = input.readStringRequireUtf8();

              data_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProtobuf.internal_static_Connection_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProtobuf.internal_static_Connection_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Connection.class, Builder.class);
    }

    public static final int SRCPUBLICKEY_FIELD_NUMBER = 1;
    private volatile Object srcPublicKey_;
    /**
     * <code>string srcPublicKey = 1;</code>
     * @return The srcPublicKey.
     */
    @Override
    public String getSrcPublicKey() {
      Object ref = srcPublicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        srcPublicKey_ = s;
        return s;
      }
    }
    /**
     * <code>string srcPublicKey = 1;</code>
     * @return The bytes for srcPublicKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getSrcPublicKeyBytes() {
      Object ref = srcPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        srcPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESTPUBLICKEY_FIELD_NUMBER = 2;
    private volatile Object destPublicKey_;
    /**
     * <code>string destPublicKey = 2;</code>
     * @return The destPublicKey.
     */
    @Override
    public String getDestPublicKey() {
      Object ref = destPublicKey_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        destPublicKey_ = s;
        return s;
      }
    }
    /**
     * <code>string destPublicKey = 2;</code>
     * @return The bytes for destPublicKey.
     */
    @Override
    public com.google.protobuf.ByteString
        getDestPublicKeyBytes() {
      Object ref = destPublicKey_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        destPublicKey_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PORT_FIELD_NUMBER = 3;
    private volatile Object port_;
    /**
     * <code>string port = 3;</code>
     * @return The port.
     */
    @Override
    public String getPort() {
      Object ref = port_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        port_ = s;
        return s;
      }
    }
    /**
     * <code>string port = 3;</code>
     * @return The bytes for port.
     */
    @Override
    public com.google.protobuf.ByteString
        getPortBytes() {
      Object ref = port_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        port_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IPV6_FIELD_NUMBER = 4;
    private volatile Object ipv6_;
    /**
     * <code>string ipv6 = 4;</code>
     * @return The ipv6.
     */
    @Override
    public String getIpv6() {
      Object ref = ipv6_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        ipv6_ = s;
        return s;
      }
    }
    /**
     * <code>string ipv6 = 4;</code>
     * @return The bytes for ipv6.
     */
    @Override
    public com.google.protobuf.ByteString
        getIpv6Bytes() {
      Object ref = ipv6_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        ipv6_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ORDER_FIELD_NUMBER = 5;
    private long order_;
    /**
     * <code>uint64 order = 5;</code>
     * @return The order.
     */
    @Override
    public long getOrder() {
      return order_;
    }

    public static final int MSGTYPE_FIELD_NUMBER = 6;
    private int msgType_;
    /**
     * <code>int32 msgType = 6;</code>
     * @return The msgType.
     */
    @Override
    public int getMsgType() {
      return msgType_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 7;
    private volatile Object signature_;
    /**
     * <code>string signature = 7;</code>
     * @return The signature.
     */
    @Override
    public String getSignature() {
      Object ref = signature_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        signature_ = s;
        return s;
      }
    }
    /**
     * <code>string signature = 7;</code>
     * @return The bytes for signature.
     */
    @Override
    public com.google.protobuf.ByteString
        getSignatureBytes() {
      Object ref = signature_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        signature_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TIMESTAMP_FIELD_NUMBER = 8;
    private long timestamp_;
    /**
     * <code>uint64 timestamp = 8;</code>
     * @return The timestamp.
     */
    @Override
    public long getTimestamp() {
      return timestamp_;
    }

    public static final int DATA_FIELD_NUMBER = 9;
    private volatile Object data_;
    /**
     * <code>string data = 9;</code>
     * @return The data.
     */
    @Override
    public String getData() {
      Object ref = data_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        data_ = s;
        return s;
      }
    }
    /**
     * <code>string data = 9;</code>
     * @return The bytes for data.
     */
    @Override
    public com.google.protobuf.ByteString
        getDataBytes() {
      Object ref = data_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        data_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcPublicKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, srcPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destPublicKey_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, destPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, port_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipv6_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, ipv6_);
      }
      if (order_ != 0L) {
        output.writeUInt64(5, order_);
      }
      if (msgType_ != 0) {
        output.writeInt32(6, msgType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, signature_);
      }
      if (timestamp_ != 0L) {
        output.writeUInt64(8, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 9, data_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(srcPublicKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, srcPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(destPublicKey_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, destPublicKey_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(port_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, port_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(ipv6_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, ipv6_);
      }
      if (order_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, order_);
      }
      if (msgType_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, msgType_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(signature_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, signature_);
      }
      if (timestamp_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(8, timestamp_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(data_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(9, data_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Connection)) {
        return super.equals(obj);
      }
      Connection other = (Connection) obj;

      if (!getSrcPublicKey()
          .equals(other.getSrcPublicKey())) return false;
      if (!getDestPublicKey()
          .equals(other.getDestPublicKey())) return false;
      if (!getPort()
          .equals(other.getPort())) return false;
      if (!getIpv6()
          .equals(other.getIpv6())) return false;
      if (getOrder()
          != other.getOrder()) return false;
      if (getMsgType()
          != other.getMsgType()) return false;
      if (!getSignature()
          .equals(other.getSignature())) return false;
      if (getTimestamp()
          != other.getTimestamp()) return false;
      if (!getData()
          .equals(other.getData())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SRCPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getSrcPublicKey().hashCode();
      hash = (37 * hash) + DESTPUBLICKEY_FIELD_NUMBER;
      hash = (53 * hash) + getDestPublicKey().hashCode();
      hash = (37 * hash) + PORT_FIELD_NUMBER;
      hash = (53 * hash) + getPort().hashCode();
      hash = (37 * hash) + IPV6_FIELD_NUMBER;
      hash = (53 * hash) + getIpv6().hashCode();
      hash = (37 * hash) + ORDER_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getOrder());
      hash = (37 * hash) + MSGTYPE_FIELD_NUMBER;
      hash = (53 * hash) + getMsgType();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + TIMESTAMP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimestamp());
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Connection parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Connection parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Connection parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Connection parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Connection parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Connection parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Connection parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Connection parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Connection parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Connection parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Connection parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Connection parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Connection prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Connection}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Connection)
        ConnectionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MsgProtobuf.internal_static_Connection_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MsgProtobuf.internal_static_Connection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Connection.class, Builder.class);
      }

      // Construct using com.revers.rec.domain.protobuf.MsgProtobuf.Connection.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        srcPublicKey_ = "";

        destPublicKey_ = "";

        port_ = "";

        ipv6_ = "";

        order_ = 0L;

        msgType_ = 0;

        signature_ = "";

        timestamp_ = 0L;

        data_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MsgProtobuf.internal_static_Connection_descriptor;
      }

      @Override
      public Connection getDefaultInstanceForType() {
        return Connection.getDefaultInstance();
      }

      @Override
      public Connection build() {
        Connection result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Connection buildPartial() {
        Connection result = new Connection(this);
        result.srcPublicKey_ = srcPublicKey_;
        result.destPublicKey_ = destPublicKey_;
        result.port_ = port_;
        result.ipv6_ = ipv6_;
        result.order_ = order_;
        result.msgType_ = msgType_;
        result.signature_ = signature_;
        result.timestamp_ = timestamp_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Connection) {
          return mergeFrom((Connection)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Connection other) {
        if (other == Connection.getDefaultInstance()) return this;
        if (!other.getSrcPublicKey().isEmpty()) {
          srcPublicKey_ = other.srcPublicKey_;
          onChanged();
        }
        if (!other.getDestPublicKey().isEmpty()) {
          destPublicKey_ = other.destPublicKey_;
          onChanged();
        }
        if (!other.getPort().isEmpty()) {
          port_ = other.port_;
          onChanged();
        }
        if (!other.getIpv6().isEmpty()) {
          ipv6_ = other.ipv6_;
          onChanged();
        }
        if (other.getOrder() != 0L) {
          setOrder(other.getOrder());
        }
        if (other.getMsgType() != 0) {
          setMsgType(other.getMsgType());
        }
        if (!other.getSignature().isEmpty()) {
          signature_ = other.signature_;
          onChanged();
        }
        if (other.getTimestamp() != 0L) {
          setTimestamp(other.getTimestamp());
        }
        if (!other.getData().isEmpty()) {
          data_ = other.data_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Connection parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Connection) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object srcPublicKey_ = "";
      /**
       * <code>string srcPublicKey = 1;</code>
       * @return The srcPublicKey.
       */
      public String getSrcPublicKey() {
        Object ref = srcPublicKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          srcPublicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string srcPublicKey = 1;</code>
       * @return The bytes for srcPublicKey.
       */
      public com.google.protobuf.ByteString
          getSrcPublicKeyBytes() {
        Object ref = srcPublicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          srcPublicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string srcPublicKey = 1;</code>
       * @param value The srcPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setSrcPublicKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        srcPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string srcPublicKey = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSrcPublicKey() {
        
        srcPublicKey_ = getDefaultInstance().getSrcPublicKey();
        onChanged();
        return this;
      }
      /**
       * <code>string srcPublicKey = 1;</code>
       * @param value The bytes for srcPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setSrcPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        srcPublicKey_ = value;
        onChanged();
        return this;
      }

      private Object destPublicKey_ = "";
      /**
       * <code>string destPublicKey = 2;</code>
       * @return The destPublicKey.
       */
      public String getDestPublicKey() {
        Object ref = destPublicKey_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          destPublicKey_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string destPublicKey = 2;</code>
       * @return The bytes for destPublicKey.
       */
      public com.google.protobuf.ByteString
          getDestPublicKeyBytes() {
        Object ref = destPublicKey_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          destPublicKey_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string destPublicKey = 2;</code>
       * @param value The destPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setDestPublicKey(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        destPublicKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string destPublicKey = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDestPublicKey() {
        
        destPublicKey_ = getDefaultInstance().getDestPublicKey();
        onChanged();
        return this;
      }
      /**
       * <code>string destPublicKey = 2;</code>
       * @param value The bytes for destPublicKey to set.
       * @return This builder for chaining.
       */
      public Builder setDestPublicKeyBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        destPublicKey_ = value;
        onChanged();
        return this;
      }

      private Object port_ = "";
      /**
       * <code>string port = 3;</code>
       * @return The port.
       */
      public String getPort() {
        Object ref = port_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          port_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string port = 3;</code>
       * @return The bytes for port.
       */
      public com.google.protobuf.ByteString
          getPortBytes() {
        Object ref = port_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          port_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string port = 3;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        port_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string port = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        
        port_ = getDefaultInstance().getPort();
        onChanged();
        return this;
      }
      /**
       * <code>string port = 3;</code>
       * @param value The bytes for port to set.
       * @return This builder for chaining.
       */
      public Builder setPortBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        port_ = value;
        onChanged();
        return this;
      }

      private Object ipv6_ = "";
      /**
       * <code>string ipv6 = 4;</code>
       * @return The ipv6.
       */
      public String getIpv6() {
        Object ref = ipv6_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          ipv6_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string ipv6 = 4;</code>
       * @return The bytes for ipv6.
       */
      public com.google.protobuf.ByteString
          getIpv6Bytes() {
        Object ref = ipv6_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          ipv6_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string ipv6 = 4;</code>
       * @param value The ipv6 to set.
       * @return This builder for chaining.
       */
      public Builder setIpv6(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        ipv6_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string ipv6 = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearIpv6() {
        
        ipv6_ = getDefaultInstance().getIpv6();
        onChanged();
        return this;
      }
      /**
       * <code>string ipv6 = 4;</code>
       * @param value The bytes for ipv6 to set.
       * @return This builder for chaining.
       */
      public Builder setIpv6Bytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        ipv6_ = value;
        onChanged();
        return this;
      }

      private long order_ ;
      /**
       * <code>uint64 order = 5;</code>
       * @return The order.
       */
      @Override
      public long getOrder() {
        return order_;
      }
      /**
       * <code>uint64 order = 5;</code>
       * @param value The order to set.
       * @return This builder for chaining.
       */
      public Builder setOrder(long value) {
        
        order_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 order = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearOrder() {
        
        order_ = 0L;
        onChanged();
        return this;
      }

      private int msgType_ ;
      /**
       * <code>int32 msgType = 6;</code>
       * @return The msgType.
       */
      @Override
      public int getMsgType() {
        return msgType_;
      }
      /**
       * <code>int32 msgType = 6;</code>
       * @param value The msgType to set.
       * @return This builder for chaining.
       */
      public Builder setMsgType(int value) {
        
        msgType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 msgType = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMsgType() {
        
        msgType_ = 0;
        onChanged();
        return this;
      }

      private Object signature_ = "";
      /**
       * <code>string signature = 7;</code>
       * @return The signature.
       */
      public String getSignature() {
        Object ref = signature_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          signature_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string signature = 7;</code>
       * @return The bytes for signature.
       */
      public com.google.protobuf.ByteString
          getSignatureBytes() {
        Object ref = signature_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          signature_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string signature = 7;</code>
       * @param value The signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignature(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }
      /**
       * <code>string signature = 7;</code>
       * @param value The bytes for signature to set.
       * @return This builder for chaining.
       */
      public Builder setSignatureBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        signature_ = value;
        onChanged();
        return this;
      }

      private long timestamp_ ;
      /**
       * <code>uint64 timestamp = 8;</code>
       * @return The timestamp.
       */
      @Override
      public long getTimestamp() {
        return timestamp_;
      }
      /**
       * <code>uint64 timestamp = 8;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        
        timestamp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>uint64 timestamp = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        
        timestamp_ = 0L;
        onChanged();
        return this;
      }

      private Object data_ = "";
      /**
       * <code>string data = 9;</code>
       * @return The data.
       */
      public String getData() {
        Object ref = data_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          data_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string data = 9;</code>
       * @return The bytes for data.
       */
      public com.google.protobuf.ByteString
          getDataBytes() {
        Object ref = data_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          data_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string data = 9;</code>
       * @param value The data to set.
       * @return This builder for chaining.
       */
      public Builder setData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string data = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      /**
       * <code>string data = 9;</code>
       * @param value The bytes for data to set.
       * @return This builder for chaining.
       */
      public Builder setDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        data_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Connection)
    }

    // @@protoc_insertion_point(class_scope:Connection)
    private static final Connection DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Connection();
    }

    public static Connection getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Connection>
        PARSER = new com.google.protobuf.AbstractParser<Connection>() {
      @Override
      public Connection parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Connection(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Connection> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Connection> getParserForType() {
      return PARSER;
    }

    @Override
    public Connection getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Connection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Connection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021MsgProtocal.proto\"\251\001\n\nConnection\022\024\n\014sr" +
      "cPublicKey\030\001 \001(\t\022\025\n\rdestPublicKey\030\002 \001(\t\022" +
      "\014\n\004port\030\003 \001(\t\022\014\n\004ipv6\030\004 \001(\t\022\r\n\005order\030\005 \001" +
      "(\004\022\017\n\007msgType\030\006 \001(\005\022\021\n\tsignature\030\007 \001(\t\022\021" +
      "\n\ttimestamp\030\010 \001(\004\022\014\n\004data\030\t \001(\tB-\n\036com.r" +
      "evers.rec.domain.protobufB\013MsgProtobufb\006" +
      "proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_Connection_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_Connection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Connection_descriptor,
        new String[] { "SrcPublicKey", "DestPublicKey", "Port", "Ipv6", "Order", "MsgType", "Signature", "Timestamp", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
